- LeetCode/Clone Graph (LEETCODE).cpp
> Clone graph code

- Java/Rectangle pattern.java
Added Rectangle pattern
Hacktoberfest 2021
> Rectangle pattern

- Minimum Cost to cut a board into squares.cpp
Added Minimum Cost to cut a board into squares
Hacktoberfest 2021
> Minimum Cost to cut a board into squares✅✨

- LeetCode/Number of Pairs of Strings With Concatenation Equal to Target.java
Add 2023. Number of Pairs of Strings With Concatenation Equal to Target java solution
> Add problem number 2023 java solution

- LeetCode/Maximize the Confusion of an Exam.java
Add 2024. Maximize the Confusion of an Exam java solution
> Create Maximize the Confusion of an Exam.java

- hamming.cpp
> Hamming Code 

- CodeChef/Practice/PROBDIFF.cpp
Hacktober Fest 2021
added : https://www.codechef.com/AUG21C/problems/PROBDIFF
> Problem Code: PROBDIFF Added

- CodeChef/September 2021 Long Challenge/Travel Pass/readme.md
- CodeChef/September 2021 Long Challenge/Travel Pass/travel_pass.cpp
The link to the problem is added to the readme file.
Please merge the PR and add the Hacktober fest tag.
> Added code to Travel Pass Problem | Codechef

- CodeChef/September 2021 Long Challenge/Airline Restrictions/airline.cpp
- CodeChef/September 2021 Long Challenge/Airline Restrictions/readme.md
- CodeChef/September 2021 Long Challenge/Shufling Parities/readme.md
- CodeChef/September 2021 Long Challenge/Shufling Parities/shuffling_parites.cpp
The link to the problems is added to the respective readme files.
Please merge the PR and add hacktober fest tag.
> Added code to Airline Restrictions & Shuffling Parities | Codchef

- DSA 450/String/FirstRepeated.cpp
followed the steps and added firstRepeated.cpp file in strings directory,
> added firstRepeated.cpp

- CodeChef/September 2021 Long Challenge/xor equal.cpp
- Codeforces/golden plate.cpp
Solution of codeforces problem.
problem link - https://codeforces.com/problemset/problem/1031/A
> Golden plate

- LeetCode/Final Value of Variable After Performing Operations.cpp
Created cpp for solution of leetcode problem 2011.
> Create Final Value of Variable After Performing Operations.cpp

- spewing.cpp
Solution of codechef problem.
problem link - https://www.codechef.com/problems/POSSPEW
> POSITIVE SPEWING

- Codeforces/Vanya_and_Lanterns.cpp
the binary-search approach, Vanya and Lanterns it is one of the good CF questions for beginners
> Vanya and Lanterns

- CodeChef/October Long Challenge 2021/LongestANDSubarray.cpp
- CodeChef/October Long Challenge 2021/MEX-OR.cpp
- CodeChef/October Long Challenge 2021/Three Boxes.cpp
- CodeChef/October Long Challenge 2021/Which Mixture.cpp
- Folder Created inside CodeChef Directory with name ' October Long Challenge 2021 '
- First Three Programs added
- With reference to issue #18
> October Long Challenge 🚀

- GRAPHS/BreadthFirstSearch.cpp
- GRAPHS/DepthFirstSearchUsingSTL.cpp
- GRAPHS/Kruskal'sMinSpanningTree.cpp
- GRAPHS/PrimsMinSpanningTree.cpp
- TREE/AVLTREE.C
- TREE/BST.C
- TREE/BST.cpp
- TREE/DeletionAVL.cpp
- TREE/Tree.c
- TREE/Tree.cpp
- sorting_algorithm_code/BubbleSort.cpp
- sorting_algorithm_code/Bucket-BinSort.cpp
- sorting_algorithm_code/InsertionSort.cpp
- sorting_algorithm_code/IterativeMergeSort.cpp
- sorting_algorithm_code/RadixSort.cpp
- sorting_algorithm_code/RecursiveMergeSort.cpp
- sorting_algorithm_code/SelectionSort.cpp
- sorting_algorithm_code/ShellSort.cpp
Added more files on Graphs, Trees, and Sorting Algorithms in C and C++ language.
Issue - #18
> Added Graphs, Trees and Sorting Algorithms source code

- Boy or Girl.cpp
- Next Round.cpp
Solution of Competitive programming problem.
Problem link - https://codeforces.com/gym/331286/problem/A
> Create Next Round.cpp

- LeetCode/Reconstruct Original Digits from English.cpp
I have solved a leetcode problem: -
https://leetcode.com/problems/reconstruct-original-digits-from-english/
Please Merge it.
Thankyou.
> Create LeetCode_Reconstruct Original Digits from English.cpp

- Sorting_algorithm_code/bubble_sort.cpp
- Sorting_algorithm_code/insertion_sort.cpp
- Sorting_algorithm_code/merge_sort.cpp
respected sir,
I have added some more sorting algorithm codes.
1) bubble sort
2) insertion sort
3) merge sort
> Sorting algorithms code

- LeetCode/Best Time to Buy and Sell Stock.cpp
I have added the solution to LeetCode problem #121. Best Time to Buy and Sell Stock in C++ language. Please merge and accept this as hacktoberfest-accepted.
> Create Best Time to Buy and Sell Stock.cpp

- DSA 450/String/Reverse String.cpp
Instead of using an extra variable, swap function is used to swap two elements.
> Update Reverse String.cpp

- All Languages/C++ Codes/Minimize_the_height.cpp
added a code for the possible minimum difference of the height of shortest and longest towers after you have modified each tower.
> program for Minimize_the_height

- Coding Platforms(codechef,codeforces,etc)/LeetCode/231. Power of Two.py
> Added Solution for Leetcode Question 231

- All Algorithms/Graph Algorithm/Prim's Algorithms.
This resolve #307 .
Plz merge it into main branch
> Create Prim's Algorithms.

- DSA 450/Binary Trees/How to test the file.txt
- DSA 450/Binary Trees/print_all_left_child_elements.cpp
added print_all_left_child_elements.cpp  and txt file.
Please merge the PR with hactorberfest label . I am newbie as contribrutor.
> added print_all_left_child_elements.cpp

- All Algorithms/Algebraic algorithms/BinaryExponentiation.cpp
Added Algebraic Algorithms folder which will contain all the Algebraic Algorithms. Binary Exponentiation is one such type and will be adding more Algebraic algorithms in future commits.
> Added Binary Exponentiation in Algebraic Algorithms

- All Data Structures/GRAPHS/BellmanfordAlgo.cpp
- All Data Structures/GRAPHS/FloydWarshall.cpp
- All Data Structures/GRAPHS/dijkstra.cpp
I hope my contributions to your repo would be much helpful. 
**Happy Hacktoberfest!!!** ❤️
> Graphs Algo Updated

- All Data Structures/Singly_LL/142-Linked-List-Cycle-II.cpp
Please merge my pull request for hacktoberfest 2022.
> 142-Linked-List-Cycle-II.cpp

- All Data Structures/Arrays/Reverse_an_array_in_python.py
- All Languages/Python Codes/Read_JSON_file_using_python.py
Added code for reversing an array in python.
> Created Reverse_an_array_in_python.py

- Coding Platforms(codechef,codeforces,etc)/Codeforces/C_1692.cpp
- Coding Platforms(codechef,codeforces,etc)/Codeforces/D_1692.cpp
Added 2 solutions of codeforces round 1692 - C and D
> added codeforces solutions

- Coding Platforms(codechef,codeforces,etc)/Codeforces/1141A.cpp
- Coding Platforms(codechef,codeforces,etc)/Codeforces/1182A.cpp
- Coding Platforms(codechef,codeforces,etc)/Codeforces/118B.cpp
- Coding Platforms(codechef,codeforces,etc)/Codeforces/1206B.cpp
- Coding Platforms(codechef,codeforces,etc)/Codeforces/1467A.cpp
- Coding Platforms(codechef,codeforces,etc)/Codeforces/1469A.cpp
- Coding Platforms(codechef,codeforces,etc)/Codeforces/1471A.cpp
- Coding Platforms(codechef,codeforces,etc)/Codeforces/1490B.cpp
- Coding Platforms(codechef,codeforces,etc)/Codeforces/1607B.cpp
- Coding Platforms(codechef,codeforces,etc)/Codeforces/766A.cpp
Added 10 codeforces question . Please accept my PR :) .
> added 10 codeforces question

- DSA 450/Dynamic Programming/Longest_Palindromic_Subsequence.cpp
hey @anupam-kumar-krishnan plz check and tell is it ok or not ?
> Added Longest Palindromic Subsequence code

- All Languages/Python Codes/QRGenerator.py
> added QR generator script

- All Languages/C++ Codes/Binary_Heap.cpp
Directory Added: 
> All Languages/C++ Codes
@anupam-kumar-krishnan
> Binary Heap

- Coding Platforms(codechef,codeforces,etc)/LeetCode/Sliding Window Maximum.cpp
Added Leetcode problem Sliding Window Maximum with proper description and comments
Link - https://leetcode.com/problems/sliding-window-maximum/
> Added Sliding Window Maximum (Leetcode)

- Basic Programming/sum_of_ap.cpp
> created sum of AP

- Coding Platforms(codechef,codeforces,etc)/CodeChef/Practice/Valid Triangles.cpp
Question Link: https://www.codechef.com/problems/FLOW013?tab=statement
> Create Valid Triangles.cpp

- Coding Platforms(codechef,codeforces,etc)/LeetCode/longest-palindrome.php
Hey guys!
I have added the Longest Palindrome resolution in PHP for LeetCode.
Best Regards
> Add longest palindrome resolution in PHP

- All Languages/Java Codes/Factorial.java
https://github.com/anupam-kumar-krishnan/Competitive_Programming/issues/393
Added factorial program in java inside [All Languages]/[Java Codes] folder
> Added Factorial program in java

- All Languages/C++ Codes/CharCountInString.cpp
-Added c++ code of "Count of character, spaces, alphabets in a string"
> Added Character Count Code

- All Algorithms/Kadane's Algorithm/Kadane's Algorithm DP.cpp
- Coding Platforms(codechef,codeforces,etc)/LeetCode/23. Merge k Sorted Lists.cpp
Kadane's Algorithm is an iterative dynamic programming algorithm. It calculates the maximum sum subarray ending at a particular position by using the maximum sum subarray ending at the previous position.
> feat: kadane's algorithm in short using dp

- Coding Platforms(codechef,codeforces,etc)/LeetCode/Arithmetic_Slices.cpp
Added a dynamic programming problem Arithmetic slices in CPP
> Added a Leetcode problem

- All Data Structures/Singly_LL/menu_based_singly_linked_list.cpp
_Following are the changes I made in [this](https://github.com/anupam-kumar-krishnan/Competitive_Programming/tree/main/All%20Data%20Structures/Singly_LL) directory of this repo:_
- Added **Linked List** program file in CPP.
- Modified the file to add all the **possible operations** we can perform on the Singly Linked List.
- **Optimized the code** and made the variables more readable for sake of understanding.
> Implementation of All Possible Operations on Linked List

- Coding Platforms(codechef,codeforces,etc)/CodeChef/Practice/odd_pairs.cpp
I have added solution for the problem [Odd Pairs](https://www.codechef.com/START53D/problems/ODDPAIRS) from codechef.
> Added odd pairs

- Basic Programming/C Program without main.c
Please merge this PR for Hacktoberfest
> Create C Program without main.c

- All Data Structures/GRAPHS/rottenOranges.cpp
a new graph question rotten oranges is added
> added rottenOranges.cpp

- Coding Platforms(codechef,codeforces,etc)/HackerRank/Create C++ Class Template Specialization.cpp
Question Link is https://www.hackerrank.com/challenges/cpp-class-template-specialization/copy-from/192283364
> Create Create C++ Class Template Specialization.cpp

- Coding Platforms(codechef,codeforces,etc)/CodeChef/Codechef-October-Long-Challenge-2022/Building_Race.cpp
- Coding Platforms(codechef,codeforces,etc)/CodeChef/Codechef-October-Long-Challenge-2022/SingleOp1.cpp
- Coding Platforms(codechef,codeforces,etc)/CodeChef/Codechef-October-Long-Challenge-2022/SingleOp2.cpp
Please tag me with hacktober fest accepted.
> Codechef October Long Challenge 2022 DIV-3

- All Algorithms/Sorting Algorithm/INSERTION SORT.cpp
An array is provided in unsorted manner.
Sort it using Insertion sort algorithm.
Show array elements before and after sorting.
> INSERTION SORT USING C++

- Coding Platforms(codechef,codeforces,etc)/LeetCode/42. Trapping Rain Water.py
leetcode solution with suitable comments
> added leetcode solution

- Coding Platforms(codechef,codeforces,etc)/LeetCode/Asteroid Collision.py
https://leetcode.com/problems/asteroid-collision/
> Create Asteroid Collision.py

- All Languages/C++ Codes/Sticks and Rectangles.cpp
Hope this helps your repository. Any form of feedback/suggestion is appreciated.
> added Sticks and Rectangles Codechef solution

- All Languages/C++ Codes/longestIncreaseSubsequence.cpp
Added Program to C++ codes section
> Added DP Program on Longest Increasing Subsequence

- All Data Structures/Queues/queueUsingLinkedList.cpp
Please merge my pull request for hacktober fest.
> Added queue implementation using linked list

- Coding Platforms(codechef,codeforces,etc)/LeetCode/Leetode_32_Longest_Valid_Parentheses.cpp
Example 1:
Input: s = "(()"
Output: 2
Explanation: The longest valid parentheses substring is "()".
Example 2:
Input: s = ")()())"
Output: 4
Explanation: The longest valid parentheses substring is "()()".
Example 3:
Input: s = ""
Output: 0
> code for longest valid parantheses

- Coding Platforms(codechef,codeforces,etc)/LeetCode/Climbing stairs.java
- Coding Platforms(codechef,codeforces,etc)/LeetCode/Coin change.java
- Coding Platforms(codechef,codeforces,etc)/LeetCode/Decode ways.java
- Coding Platforms(codechef,codeforces,etc)/LeetCode/Jump game.java
- Coding Platforms(codechef,codeforces,etc)/LeetCode/Longest increasing subsequence.java
- Coding Platforms(codechef,codeforces,etc)/LeetCode/Word break.java
- Coding Platforms(codechef,codeforces,etc)/LeetCode/house robber.java
- Coding Platforms(codechef,codeforces,etc)/LeetCode/house robber2.java
- Coding Platforms(codechef,codeforces,etc)/LeetCode/merge k sorted lists.java
- Coding Platforms(codechef,codeforces,etc)/LeetCode/word search II.java
Verify my submissions and assign me hacktoberfest labels. If there is any changes required, let me know.
> Added leetcode qus using java

- All Data Structures/Stack/stack using linked list (doubly pointer)
please add hacktoberfest-added label
> Create stack using linked list (doubly pointer)

- DSA 450/Dynamic Programming/Longest_common_subsequence.cpp
Added Longest Common Sub sequence Code
> longest common subsequence added

- All Languages/Python Codes/YTDownloader.py
Downloads Youtube Video From Link
Requires: Pytube module
> added Youtube Video Downloader

- All Algorithms/SortColors.java
> Dutch National Flag Algorithm

- Coding Platforms(codechef,codeforces,etc)/LeetCode/1255.Maximum Score Words Formed by Letters
cpp code for leetcode problem 1255.Maximum Score Words Formed by Letters
> leetcode 1255

- Basic Programming/Insertion_Sort.cpp
- Basic Programming/counting Sort.cpp
- Basic Programming/selection_sort.cpp
Added counting, selection, insertion sort
> Sorting algorithm

- All Algorithms/Dynamic Programming/LIS/LongestIncreasingSubsequence_Recursive.java
LIS problem Recursive implementation
> LongestIncreasingSubsequence_Recursive.java

- DSA 450/Dynamic Programming/UniqueBinarySearchTree.cpp
here we use the property of the pascal traingle to calculate the total no of bst that is 2*nCn/(n+1);
> UniqueBinarySearchTree

- Coding Platforms(codechef,codeforces,etc)/LeetCode/17. Letter Combinations of a Phone Number.cpp
Added leetcode problem 17. Letter Combinations of a Phone Number
> Added problem to leetcode folder

- All Languages/Java Codes/tictactoe.java
> Tic Tac Toe Game in Java

- All Algorithms/strassen.cpp
> strassen's matrix multiplication algorithm #393

- DSA 450/Arrays/33.Minimum_no_required_palindrome.cpp
I have tested the Codebase on all the edge and boundary cases. PR is ready to go.
> adding 33th question of cpp

- Basic Programming/1192-critical-connections-in-a-network.cpp
1192-critical-connections-in-a-network.cpp
> 1192-critical-connections-in-a-network.cpp

- Coding Platforms(codechef,codeforces,etc)/LeetCode/SpiralMatrix.java
Please accept my pull request for the code of spiral matrix.
> 54. Spiral Matrix

- DSA 450/Arrays/34. Median of two arrays.py
> Create 34. Median of two arrays.py

- All Languages/Java Codes/duplicate elements of an array.java
Added duplicate element in array
> Duplicate Element

- Coding Platforms(codechef,codeforces,etc)/HackerRank/SubArrayDiv.Cpp
It is the solution to HackerRank Subarray Division Problem.
> SubArray Division

- All Algorithms/Algebraic algorithms/strassen_matrix.c
- strassen_matrix.c
Please, Accept my PR and add hacktober accepted tag to it. Thank you.
> Added Strassen matrix code

- All Data Structures/Binary Search Tree/One_way_right_threaded_BST.c
Please, Accept and Approve My PR and add hacktober accepted tag to it.
> Added one_way_right_threaded_BST code.

- All Algorithms/Sorting Algorithm/merge_sort.c.c
Please, Approve My PR and add hacktober accepted tag to it.
> Added Merge_sort code.

- All Languages/Python Codes/fizzbuzz.py
adding a python fizzbuzz program
> Create fizzbuzz programm

- All Data Structures/Singly_LL/linkedlist.cpp
linked list using classes in cpp
> linked lists program in cpp

- All Data Structures/Sorting/Radix Sort Code in cpp
> Following is the code for Radix Sort in cpp

- All Data Structures/CircularLinkedList/circular_doubly_linked_list.c
- All Data Structures/CircularLinkedList/circular_singly_linked_list.c
added circular linked list data structure (both singly and doubly)
> added circular linked list

- randomized_quick_sort.c
Please, Accept and Approve My PR and add hacktoberfest accepted tag to it.
> Added Randomized Quick_sort code.

- All Algorithms/Sorting Algorithm/Randomized_Quicksort.c
- Randomized_Quicksort.c
> Randomized quick sort

- DSA 450/Linked List/addTwoNumbersRepresentedByLinkedList.cpp
name - anubhav404
git hub - https://github.com/anubhav404
> added  linked list code in c++ language

- All Data Structures/linear_search_algo.cpp
> created linear_search.cpp

- Coding Platforms(codechef,codeforces,etc)/LeetCode/809.ExpressiveWords.cpp
I worked on Problem 809. Expressive Words .
> 'ExpressiveWords'

- All Data Structures/Arrays/Cheapest Path CodeChef.cpp
Hi, I have added the solution for the question: https://www.codechef.com/ZCOPRAC/problems/ZCO22001?tab=statement in C++.
> Added CPP Code for Cheapest Path in Binary Vector

- All Algorithms/Boyer_Moore_Majority_Voting_Algorithm.cpp
Created the PR for this open issue  #393 
Have added this in the Algorithm folder.
Kindly review and let me know if any changes are required  @anupam-kumar-krishnan !!
Thanks!!
> Added code for Majority element using Moores voting Algo 

- All Data Structures/Stack/Trapping_rain_water.cpp
I have added leetcode 42 solution in cpp
> added leetcode trapping rain water problem

- Coding Platforms(codechef,codeforces,etc)/Codeforces/746B.cpp
Here is my C++ solution to Codeforces 746B problem.
> Add Codeforces 746B problem

- Coding Platforms(codechef,codeforces,etc)/CodeChef/Starters 62/CHEFSCORE.cpp
- Coding Platforms(codechef,codeforces,etc)/CodeChef/Starters 62/FINALSUM.cpp
- Coding Platforms(codechef,codeforces,etc)/CodeChef/Starters 62/MAKEMULTIPLE.cpp
- Coding Platforms(codechef,codeforces,etc)/CodeChef/Starters 62/MAXDIFFMIN.cpp
- Coding Platforms(codechef,codeforces,etc)/CodeChef/Starters 62/SSUBSTR.cpp
- Coding Platforms(codechef,codeforces,etc)/CodeChef/Starters 62/XJUMP.cpp
Solution of problems that I solved in starters 62 of codechef
> Solution of starters 62

- All Data Structures/Trie/LCPtrie.cpp
C++ program to find Longest Common Prefix using Trie Data Structure
> Longest Common Prefix

- Coding Platforms(codechef,codeforces,etc)/Codeforces/1749A.cpp
> Add Codeforces 1749A

- Coding Platforms(codechef,codeforces,etc)/CodeChef/July Long Challenge/Game of Piles Version 1.cpp
This is a question asked in July Long One 2022 Division 3
> Game of Piles Version 1

- Basic Programming/Unique_hello_world.c
Added to print Hello World without using main function
> Created Unique_hello_world.c

- All Algorithms/Algebraic algorithms/ModularExponentiation.cpp
Added Modular Exponentiation Algorithm
Link to a practise problem is also mentioned in the file
Thank you !
Happy Hacktoberfest @anupam-kumar-krishnan !
> Added ModularExponentiation.cpp

- Coding Platforms(codechef,codeforces,etc)/LeetCode Fresh Start/121. Best Time to Buy and Sell Stock.cpp
Added DP problem from LeetCode
> Added Leetcode Solution to Problem 121

- Coding Platforms(codechef,codeforces,etc)/Median of two sorted arrays of same size
There are 2 sorted arrays A and B of size n each. Write an algorithm to find the median of the array obtained after merging the above 2 arrays(i.e. array of length 2n). The complexity should be O(log(n))
> Create Median of two sorted arrays of same size

- All Algorithms/Dynamic Programming/LIS/Knapsack with repititions.cpp
Pls merge my contribution and add Hacktoberfest accepted tag
> Knapsack Added

- All Data Structures/Segment Tree/Lazy_Propagation.cpp
Issue #670 
Added Lazy Propagation algorithm code in `All Data Structures / Segment Tree`.
> Added Lazy Propagation code

- All Data Structures/Dynamic_Programming/Coin_change
> Added coin change problem with C++ solution

- All Algorithms/Graph Algorithm/Topo-Sort-BFS
Added code for Topological Sort using BFS (Breadth First Search)
Solved Issue #674 
@anupam-kumar-krishnan 
Please review the code and merge it.
> Added code for Topo-Sort-BFS

- Basic Programming/All_Patterns.c
This pull request introduces a set of C programs that generate various pyramid patterns based on user input. The patterns include right half pyramid, left half pyramid, full pyramid, inverted right half pyramid, inverted left half pyramid, inverted full pyramid, rhombus, diamond, hourglass, hollow square, hollow full pyramid, hollow inverted full pyramid, hollow diamond, and hollow hourglass.
- Added functions to print different pyramid patterns.
- Implemented user input for the number of rows to determine the size of the patterns.
- Organized the code into separate functions for each pattern for better modularity.
- Tested and validated each pattern to ensure correctness.
- Updated the main function to interactively take user input for the number of rows.
- Included a separate code for …
> Create All_Patterns.c - print all patterns in star

- All Algorithms/Sorting Algorithm in Python/tim_sort.py
Added a new sorting algorithm i.e. Tim Sort using Python
> Add tim_sort.py sorting algorithm

- Basic Programming/Max index.cpp
Added a new cpp code for finding the maximum j – i such that arr[i] <= arr[j]
> Create Max index.cpp

- All Languages/C Codes/mergesort.c
I have added a merge sort program in C. If there is any error, please tell me; otherwise, kindly merge my PR.
> Added merge sort in C

- All Languages/C Codes/bubblesort.c
I have added a bubble sort program in C. If there is any error, please tell me; otherwise, kindly merge my PR.
> Added bubble sort in C
